# Pokemon Data - Notebook n° 2

### L'objectif de ce Notebook est de vous présenter un mini-jeu qui déterminera quel starter Pokémon est fait pour vous, en se basant sur votre date de naissance ainsi que votre région de naissance, qui vous attribuera automatiquement un type ainsi qu'une génération.

In [1]:
#Importation des librairies
import pandas as pd

In [2]:
#Lecture du fichier
df = pd.read_csv("Data.csv", index_col="Pokemon Id")
pd.set_option("max_columns", None)

On commence par créer les données nécéssaires pour programmer le mini-jeu.

In [3]:
#Sélection des formes originales
df = df[df["Alternate Form Name"].isna()]

In [4]:
#Data frame composé des starters uniquement
df_starters = df.iloc[[0,3,6,
                       151,154,157,
                       251,254,257,
                       386,389,392,
                       494,497,500,
                       649,652,655,
                       721,724,727,
                       809,812,815]]

In [5]:
df_starters.head()

,Pokedex Number,Pokemon Name,Classification,Alternate Form Name,Original Pokemon ID,Legendary Type,Pokemon Height,Pokemon Weight,Primary Type,Secondary Type,Primary Ability,Primary Ability Description,Secondary Ability,Secondary Ability Description,Hidden Ability,Hidden Ability Description,Special Event Ability,Special Event Ability Description,Male Ratio,Female Ratio,Base Happiness,Game(s) of Origin,Region of Origin,Health Stat,Attack Stat,Defense Stat,Special Attack Stat,Special Defense Stat,Speed Stat,Base Stat Total,Health EV,Attack EV,Defense EV,Special Attack EV,Special Defense EV,Speed EV,EV Yield Total,Catch Rate,Experience Growth,Experience Growth Total,Experience Yield,Primary Egg Group,Secondary Egg Group,Egg Cycle Count,Pre-Evolution Pokemon Id,Evolution Details
Pokemon Id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,1,Bulbasaur,Seed Pokemon,NaN,NaN,NaN,0.7,6.9,Grass,Poison,Overgrow,Powers up Grass-type moves when the Pokémon's ...,NaN,NaN,Chlorophyll,Boosts the Pokémon's Speed stat in harsh sunli...,NaN,NaN,87.5,12.5,70,Red / Blue / Yellow,Kanto,45,49,49,65,65,45,318,0,0,0,1,0,0,1,45,Medium Slow,1059860,64,Monster,Grass,20,NaN,NaN
5,4,Charmander,Lizard Pokemon,NaN,NaN,NaN,0.6,8.5,Fire,NaN,Blaze,Powers up Fire-type moves when the Pokémon's H...,NaN,NaN,Solar Power,"Boosts the Sp. Atk stat in harsh sunlight, but...",NaN,NaN,87.5,12.5,70,Red / Blue / Yellow,Kanto,39,52,43,60,50,65,309,0,0,0,0,0,1,1,45,Medium Slow,1059860,62,Monster,Dragon,20,NaN,NaN
10,7,Squirtle,Tiny Turtle Pokemon,NaN,NaN,NaN,0.5,9.0,Water,NaN,Torrent,Powers up Water-type moves when the Pokémon's ...,NaN,NaN,Rain Dish,The Pokémon gradually regains HP in rain.,NaN,NaN,87.5,12.5,70,Red / Blue / Yellow,Kanto,44,48,65,50,64,43,314,0,0,1,0,0,0,1,45,Medium Slow,1059860,63,Monster,Water 1,20,NaN,NaN
245,152,Chikorita,Leaf Pokemon,NaN,NaN,NaN,0.9,6.4,Grass,NaN,Overgrow,Powers up Grass-type moves when the Pokémon's ...,NaN,NaN,Leaf Guard,Prevents status conditions in harsh sunlight.,NaN,NaN,87.5,12.5,70,Gold / Silver / Crystal,Johto,45,49,65,49,65,45,318,0,0,0,0,1,0,1,45,Medium Slow,1059860,64,Monster,Grass,20,NaN,NaN
248,155,Cyndaquil,Fire Mouse Pokemon,NaN,NaN,NaN,0.5,7.9,Fire,NaN,Blaze,Powers up Fire-type moves when the Pokémon's H...,NaN,NaN,Flash Fire,Powers up the Pokémon's Fire-type moves if it'...,NaN,NaN,87.5,12.5,70,Gold / Silver / Crystal,Johto,39,52,43,60,50,65,309,0,0,0,0,0,1,1,45,Medium Slow,1059860,62,Field,NaN,20,NaN,NaN

In [6]:
df_starters.tail()

,Pokedex Number,Pokemon Name,Classification,Alternate Form Name,Original Pokemon ID,Legendary Type,Pokemon Height,Pokemon Weight,Primary Type,Secondary Type,Primary Ability,Primary Ability Description,Secondary Ability,Secondary Ability Description,Hidden Ability,Hidden Ability Description,Special Event Ability,Special Event Ability Description,Male Ratio,Female Ratio,Base Happiness,Game(s) of Origin,Region of Origin,Health Stat,Attack Stat,Defense Stat,Special Attack Stat,Special Defense Stat,Speed Stat,Base Stat Total,Health EV,Attack EV,Defense EV,Special Attack EV,Special Defense EV,Speed EV,EV Yield Total,Catch Rate,Experience Growth,Experience Growth Total,Experience Yield,Primary Egg Group,Secondary Egg Group,Egg Cycle Count,Pre-Evolution Pokemon Id,Evolution Details
Pokemon Id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1249,725,Litten,Fire Cat Pokemon,NaN,NaN,NaN,0.4,4.3,Fire,NaN,Blaze,Powers up Fire-type moves when the Pokémon's H...,NaN,NaN,Intimidate,The Pokémon intimidates opposing Pokémon upon ...,NaN,NaN,87.5,12.5,70,Sun / Moon,Alola,45,65,40,60,40,70,320,0,0,0,0,0,1,1,45,Medium Slow,1059860,64,Field,NaN,15,NaN,NaN
1252,728,Popplio,Sea Lion Pokemon,NaN,NaN,NaN,0.4,7.5,Water,NaN,Torrent,Powers up Water-type moves when the Pokémon's ...,NaN,NaN,Liquid Voice,All sound-based moves become Water-type moves.,NaN,NaN,87.5,12.5,70,Sun / Moon,Alola,50,54,54,66,56,40,320,0,0,0,1,0,0,1,45,Medium Slow,1059860,64,Water 1,Field,15,NaN,NaN
1439,810,Grookey,Chimp Pokemon,NaN,NaN,NaN,0.3,5.0,Grass,NaN,Overgrow,Powers up Grass-type moves when the Pokémon's ...,NaN,NaN,Grassy Surge,Turns the ground into Grassy Terrain when the ...,NaN,NaN,87.5,12.5,50,Sword / Shield,Galar,50,65,50,40,40,65,310,0,0,0,0,1,0,1,45,Medium Slow,1059860,62,Field,Grass,20,NaN,NaN
1442,813,Scorbunny,Rabbit Pokemon,NaN,NaN,NaN,0.3,4.5,Fire,NaN,Blaze,Powers up Fire-type moves when the Pokémon's H...,NaN,NaN,Libero,Changes the Pokémon's type to the type of the ...,NaN,NaN,87.5,12.5,50,Sword / Shield,Galar,50,71,40,40,40,69,310,0,0,0,0,0,1,1,45,Medium Slow,1059860,62,Field,Human-Like,20,NaN,NaN
1445,816,Sobble,Water Lizard Pokemon,NaN,NaN,NaN,0.3,4.0,Water,NaN,Torrent,Powers up Water-type moves when the Pokémon's ...,NaN,NaN,Sniper,Powers up moves if they become critical hits w...,NaN,NaN,87.5,12.5,50,Sword / Shield,Galar,50,40,40,70,40,70,310,0,0,0,0,1,1,2,45,Medium Slow,1059860,62,Water 1,Field,20,NaN,NaN

In [7]:
df_starters.describe()

,Pokedex Number,Original Pokemon ID,Pokemon Height,Pokemon Weight,Male Ratio,Female Ratio,Base Happiness,Health Stat,Attack Stat,Defense Stat,Special Attack Stat,Special Defense Stat,Speed Stat,Base Stat Total,Health EV,Attack EV,Defense EV,Special Attack EV,Special Defense EV,Speed EV,EV Yield Total,Catch Rate,Experience Growth Total,Experience Yield,Egg Cycle Count,Pre-Evolution Pokemon Id
count,24.000000,0.0,24.000000,24.000000,24.0,24.0,24.000000,24.000000,24.000000,24.000000,24.000000,24.000000,24.000000,24.000000,24.000000,24.000000,24.000000,24.000000,24.000000,24.000000,24.000000,24.0,24.0,24.000000,24.00000,0.0
mean,436.625000,NaN,0.462500,6.708333,87.5,12.5,67.500000,48.500000,55.916667,49.333333,55.333333,50.500000,52.875000,312.458333,0.083333,0.125000,0.083333,0.250000,0.125000,0.375000,1.041667,45.0,1059860.0,62.666667,19.37500,NaN
std,274.358511,NaN,0.143898,2.359056,0.0,0.0,6.756639,7.546954,8.712393,9.648909,9.512768,7.907069,13.182045,4.211570,0.282330,0.337832,0.282330,0.442326,0.337832,0.494535,0.204124,0.0,0.0,0.916831,1.68916,NaN
min,1.000000,NaN,0.300000,1.500000,87.5,12.5,50.000000,39.000000,40.000000,35.000000,40.000000,40.000000,31.000000,307.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,45.0,1059860.0,61.000000,15.00000,NaN
25%,228.500000,NaN,0.400000,5.000000,87.5,12.5,70.000000,44.000000,49.000000,40.000000,47.250000,44.750000,42.250000,309.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,45.0,1059860.0,62.000000,20.00000,NaN
50%,444.000000,NaN,0.400000,6.950000,87.5,12.5,70.000000,47.500000,55.000000,47.000000,59.000000,50.000000,45.000000,310.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,45.0,1059860.0,62.000000,20.00000,NaN
75%,672.500000,NaN,0.500000,8.625000,87.5,12.5,70.000000,50.750000,63.500000,55.000000,62.250000,55.250000,65.000000,315.000000,0.000000,0.000000,0.000000,0.250000,0.000000,1.000000,1.000000,45.0,1059860.0,63.250000,20.00000,NaN
max,816.000000,NaN,0.900000,10.200000,87.5,12.5,70.000000,68.000000,71.000000,65.000000,70.000000,65.000000,71.000000,320.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000,45.0,1059860.0,64.000000,20.00000,NaN

In [8]:
def signe_utilisateur(jour_de_naissance,mois_de_naissance) :
    """Trouve le signe astrologique de l'utilisateur"""
    
    #Définition d'un dictionnaire
    astrologie = {
    "Bélier" : (21,3,20,4),
    "Taureau" : (21,4,21,5),
    "Gémeaux" : (22,5,21,6),
    "Cancer" : (22,6,22,7),
    "Lion" : (23,7,22,8),
    "Vierge" : (23,8,22,9),
    "Balance" : (23,9,22,10),
    "Scorpion" : (23,10,22,11),
    "Sagittaire" : (23,11,21,12),
    "Capricorne" : (22,12,20,1),
    "Verseau" : (21,1,19,2),
    "Poissons" : (20,2,20,3)
    }
    
    #Définition d'une boucle conditionnelle
    for signe, date in astrologie.items() :
        if ((jour_de_naissance>=date[0]) and (mois_de_naissance==date[1])) or ((jour_de_naissance<=date[2]) and (mois_de_naissance==date[3])) :
            return(signe)

In [9]:
def type_utilisateur(signe_utilisateur) :
    """Convertit le signe astrologique de l'utilisateur en type élémentaire"""
    
    #Définition d'un dictionnaire
    astrologie_type = {
    "Grass" : ("Gémeaux","Vierge","Balance","Capricorne"),
    "Water" : ("Cancer","Scorpion","Verseau","Poissons"),
    "Fire" : ("Bélier","Taureau","Lion","Sagittaire")
    }
    
    #Définition d'une boucle conditionnelle
    for types, signes in astrologie_type.items() :
        for signe in signes :
            if (signe_utilisateur==signe) :
                return(types)

In [10]:
def region_utilisateur(region_de_naissance) :
    """Convertit la région de l'utilisateur en région Pokemon"""
    
    #Définition d'un dictionnaire
    regions = {
        "Kanto" : ("Ile-de-France","Bretagne"),
        "Johto" : "Normandie",
        "Hoenn" : ("Occitanie","Pays de la Loire"),
        "Sinnoh" : "Nouvelle-Aquitaine",
        "Unova" : ("Provence-Alpes-Côte d’Azur","Centre-Val de Loire"),
        "Kalos" : ("Hauts-de-France","Grand Est"),
        "Alola" : "Corse",
        "Galar" : ("Auvergne-Rhône-Alpes","Bourgogne-Franche-Comté")
    }
    
    #Définition d'une boucle conditionnelle
    for regions_pokemon, regions_france in regions.items() :
        if (len(regions_france)<=2) :
            for region in regions_france :
                if (region_de_naissance==region) :
                    return(regions_pokemon)
        else :
            if (region_de_naissance==regions_france) :
                    return(regions_pokemon)

In [11]:
def pokemon_utilisateur() :
    """Convertit les critères de l'utilisateur en un starter Pokemon"""
    
    #Entrée des données utilisateur
    jour_de_naissance = int(input("Jour de naissance : "))
    mois_de_naissance = int(input("Mois de naissance : "))

    #Appel de deux fonctions
    signe = signe_utilisateur(jour_de_naissance,mois_de_naissance)
    print(f"Ton signe : {signe}")
    types = type_utilisateur(signe)
    print(f"\nTon type : {types}")
    
    #Tri du dataframe selon les données utilisateur
    df_select = df_starters[df_starters["Primary Type"]==types]
    regions = sorted(["Ile-de-France","Bretagne","Normandie","Occitanie",
               "Pays de la Loire","Nouvelle-Aquitaine","Provence-Alpes-Côte d’Azur","Centre-Val de Loire",
               "Hauts-de-France","Grand Est","Corse","Auvergne-Rhône-Alpes","Bourgogne-Franche-Comté"])
    print("\nRégion de naissance :")
    region_de_naissance = None
    while region_de_naissance not in regions :
        region_de_naissance = input(f"\n{regions}\nVotre réponse : ")
    region = region_utilisateur(region_de_naissance)
    print(f"\nTa région : {region}")
    df_select = df_select[df_select["Region of Origin"]==region]
    
    #Affichage du Pokemon
    nom_du_pokemon = df_select["Pokemon Name"]
    print(f"\nTon Pokemon : {nom_du_pokemon}")

### Vous pouvez ainsi découvrir quel est votre starter en faisant le test ci-dessous :

In [12]:
#Appel d'une fonction
pokemon_utilisateur()

Jour de naissance : 18
Mois de naissance : 12
Ton signe : Sagittaire

Ton type : Fire

Région de naissance :

['Auvergne-Rhône-Alpes', 'Bourgogne-Franche-Comté', 'Bretagne', 'Centre-Val de Loire', 'Corse', 'Grand Est', 'Hauts-de-France', 'Ile-de-France', 'Normandie', 'Nouvelle-Aquitaine', 'Occitanie', 'Pays de la Loire', 'Provence-Alpes-Côte d’Azur']
Votre réponse : Normandie

Ta région : Johto

Ton Pokemon : Pokemon Id
248    Cyndaquil
Name: Pokemon Name, dtype: object